var PermissionAction = require('./../models/permissionAction.js')

PermissionAction.bulkCreate([
  { permissionId: 1, actionId: 1 },
  { permissionId: 1, actionId: 2 },
  { permissionId: 1, actionId: 3 },
  { permissionId: 1, actionId: 4 },
  { permissionId: 1, actionId: 5 },
  { permissionId: 1, actionId: 6 },
  { permissionId: 1, actionId: 7 },
  { permissionId: 1, actionId: 8 },
  { permissionId: 1, actionId: 9 },
  { permissionId: 1, actionId: 10 },
  { permissionId: 1, actionId: 11 },
  { permissionId: 1, actionId: 12 },
  { permissionId: 1, actionId: 13 },
  { permissionId: 1, actionId: 14 },
  { permissionId: 1, actionId: 15 },
  { permissionId: 1, actionId: 16 },
  { permissionId: 1, actionId: 17 },
  { permissionId: 1, actionId: 18 },
  { permissionId: 1, actionId: 19 },
  { permissionId: 1, actionId: 20 },
  { permissionId: 1, actionId: 21 },
  { permissionId: 1, actionId: 22 },
  { permissionId: 2, actionId: 1 },
  { permissionId: 2, actionId: 3 },
  { permissionId: 2, actionId: 6 },
  { permissionId: 2, actionId: 8 },
  { permissionId: 2, actionId: 10 },
  { permissionId: 2, actionId: 11 },
  { permissionId: 2, actionId: 13 },
  { permissionId: 2, actionId: 14 },
  { permissionId: 2, actionId: 16 },
  { permissionId: 2, actionId: 17 },
  { permissionId: 2, actionId: 21 },
  { permissionId: 2, actionId: 22 }
])
