var register = require('./register.js')
var login = require('./login.js')
var checkEmail = require('./checkEmail.js')
var changePassword = require('./changePassword.js')
var isLoggedIn = require('./isLoggedIn.js')
var confirmRegistration = require('./confirmRegistration.js')
var info = require('./info.js')
var logout = require('./logout.js')
var resendConfirmRegistrationEmail = require('./resendConfirmRegistrationEmail.js')

module.exports.register = register
module.exports.login = login
module.exports.checkEmail = checkEmail
module.exports.changePassword = changePassword
module.exports.isLoggedIn = isLoggedIn
module.exports.confirmRegistration = confirmRegistration
module.exports.info = info
module.exports.logout = logout
module.exports.resendConfirmRegistrationEmail = resendConfirmRegistrationEmail
