var User = require('./../models/user.js')
var UserToken = require('./../models/userToken.js')
var Admin = require('./../models/admin.js')
var Action = require('./../models/action.js')
var Permission = require('./../models/permission.js')
var PermissionAction = require('./../models/permissionAction.js')
var Ad = require('./../models/ad.js')
var Category = require('./../models/category.js')
var MessageList = require('./../models/messageList.js')
var Message = require('./../models/message.js')

User.sync({ force: true })
UserToken.sync({ force: true })
Admin.sync({ force: true })
PermissionAction.sync({ force: true })
Action.sync({ force: true })
Permission.sync({ force: true })
Ad.sync({force: true })
Category.sync({force: true})
MessageList.sync({force:true})
Message.sync({force:true})